language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: x7Jiyxs7lnw+472vHFgtUYJrfEhl41Phz7RAVQzNQpZSGlycoVf8q9XDyRuvTKvAZvAfP5JurrqBTwx3M/oM62BLy83n082v0AMs69ytBzwoaE0ZT/HPqp/AoctkxzjfC/3l6qsUzUOppTDm0k7jHyZHywqEMShz5VRTQGpoYdW1nmGbpkShBKEf0HKvo9c79ia/t078vzhPtZ/udXyiKoJWfgLfLT67CZ3uJrqAPWqf2vzoJd5dFdUPB00N6RKabXqnpCg+A37E7TIbaVWx295yxKC3w4wA8e2KMTfyOyV9prIDhRkraZERGQsHwwRBabZIg/LyPH/l/xnW6pvMoiGG/aBMGvHMpwKJwWBidzWIyMu7HAf+Vq22jwAU1LDPr7AVgfp+krs1B6BRqGjgKHZrsY6enh3KhhUURuYBqnKFL9cOWi9i/bvO3GNh9J2idFHlAOF+YiGZ+RSjYQl3bAEDH6gImm0AC5N3NzX+kfE4UdDYPhMCjSt5/vbxx1kVN6wmKNg7gPNLdJ38rbLOYjEYSC0FIhvL2OPUAoDkXEDxpoVqdeHzzt3uvwqGqM2zbUjkm+NmL9XNDAE2kLhw5XvsvNfYLLTk4NdJ52GpexKTrYX1wPox/e5fxDOj6ld1q1soWMtJZz5Z9BKySKGwEHxtTT5wpA+FjAsfWLQ0nDg=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: true
deploy:
  provider: s3
  access_key_id: AKIAI5QXJ75WYYAXEV3A
  bucket: bertold.kolics.net
  local-dir: _site
  upload-dir: travis-builds
  acl: public_read
  skip_cleanup: true
  region: us-east-1
  on:
    repo: bertold/bertold.kolics.net
