language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: true
deploy:
  provider: s3
  access_key_id: AKIAICVXF5PN4H4LPPUA
  secret_access_key:
    secure: Sv7TivipPtdB53uCCRcY2EmY/FHWbHMq8quhtKPEHdO2Be6D79TFhlaYsrNeIkpVQSGADknoVq8piTirCtlc0Ol1/+tCUjAbJ+g0ccwbg9+9cafaTwWWGlzEOt0Qz4AIElv415M62evZKE+fAV0tEu4j75Ns74rDKBWc1A0ARUUpMeWgzsopq8Dnjuj00lrUhP+X/21zieQWqdMjXSiJZdXBJeGWUuI/hDCvyenGgQxO5ow435o1jmZFt2MenO7cIZe1FpWI7h0cCvzogANCFQSTULtc4SONDVkykfuz3ncRk4Tlquy78I+pDPqQ9YCTM4Bv/8V8Bi2UjE1ex9lQLtZlGFtLeyc7v6VUn7uF2iQXyTpwt+W4yeTHWGBOBbc0hURs6c5ap2SkBi4urK0mUNM5Tcm7B9x9xj0pAMQt4I0WeVIBUmifZT0Ts6E0LpWTV8Ajwn7nqYMWJEIvDgmqK1T/+gJQLBsjmh3Lx66epxFfw04lxI3q/rbzD3KQjbTx8VSH2qsI85UQU+pNoK/FNZNlJfDku3OagGoJDqFyuFGyAo8dQ0Fnk9vQnevb8Bu7nf0+GqYLy9JmLIKatKBxodWVso4SvmlN09eZy+1tvge6dSfon4IcqjoxovjppSlKdNEgH6qU5B2qoqZC36soHWFp/jhg+FWau+J8zBpmhwY=
  bucket: bertold.kolics.net
  local-dir: _site
  upload-dir: travis-builds
  acl: public_read
  skip_cleanup: true
  region: us-east-1
  on:
    repo: bertold/bertold.kolics.net
