language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: true
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_ACCESS_KEY_VALUE}
  bucket: bertold.kolics.net
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  region: us-east-1
  on:
    repo: bertold/bertold.kolics.net
