language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: ahyvBwy3W+CVlU4RI/4Z7TlZ0neLV2i2+Sw5inklx2vkRqsR5bfNo6BImsy/qY8G8xTCRvD9BLzrX4LLtzFVrrbClq6oXSyjFDCN934piCQL+7/uYlj7dnRiw7ukVPrceA7B7Q7lWTVyCxM+okqKP8/D/dkEd+OcaZnyMOQ3Y1dUj1fyXWl2Ce8gVwRpITVGxIY/JOOC78OAo6LA2LKSCCNoc+Xg1GZMD2ytCMI9Xw0XJodl9BHKzHL46vn9i3G7C7UUdn6hFEyVLg8c26cAr7XCKKQaYUKNRJhB5SOZJeis1luAP5lKPmxfBwJ+xE5hLkGHMCLsJTmCch0k9NBeosFd0Hs/uGZCdJMB1D/6K7+nLn2lCViYCLWlXzZadQAp6QrocddTF56LvQXbFRot5Nwin13aBGKEowVD+5/BZz+Cj1SSAHXvEcY+Tz3vgZPRzPyNaekFmGHLJHG3PtO9WMjOsu/JhHQ1U4DDLn4IYKf7G3waT4D6eUxa/I15+c2sjh4jnjoInC6dQYGZ2O+CaTEfO2VlUHHhkw7MiPP4eg08tLFaA3F1IKU8wNVmq/kPI3mrPH9Q50pC6Wr0sONjDjmuUNmraVLcOLK+Slqke2EA/tbpTLIj/hmC6tEVgK1AW4apcW1GaFGP5jN2bouE7YPLtWN4VYcqOLdZXEmTmiQ=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: true
deploy:
  provider: s3
  access_key_id: AKIAICVXF5PN4H4LPPUA
  bucket: bertold.kolics.net
  local-dir: _site
  upload-dir: travis-builds
  acl: public_read
  skip_cleanup: true
  region: us-east-1
  on:
    repo: bertold/bertold.kolics.net
Bb1a/OJ1LEyxD1JaCVFDING3NnoozhiuF3lRtfYo:
  secure: u6xD7uspwLXg31IZPQ4O0pzzztA5fvBveuTD4CehmyES1RWroV4zYNrRFh3PMeS88x27aqDQQk6cvN5tujpfSWG8CdtHD9vub4C8wRYw/Yb1GF0sw2nZk5+z3k2nV203ZBmKWaQI4j7d4AiaEww+PTt5fXEH0uozpJSVgFtJIdbleIpv11Q+FjbHsw0wUJ2nG55miLAdY0uPWna4/4CkDxKc7ZWvKXW+5H76KD78iTOuYoAM/KBTDybZCf/IxjMWxQba5oS+ydHqjizp+gk9hVjUixQYhC326aQqPfE4wDPaHiDG6DTLoilNyIOvMR9G67BkLXXqhj+OscpPcbCB35oY/CH3n2LxoYiyR2l83+tlE9Q2mAX+N8w+JLRlzy+IeJIAL1gW4KumqFnKT0YKL3VuYd5uRR+nuuX70ZqbCCxXh3FGPRcceZBGAr+NiffEFZewaQf4WQYFpvbtEXubUxgK704JGX5aDsF9qTZTZQb4AMtPqM3g+duor9XBba2nXbylyX8xl5sVDKIJRClnbzKCeIDQI+BtFA7vkd3IkNkAVaAVAUqCLGgugYKFYXi41KihX5+fyC0qyAUZxhpeyM1APdmV7IAIjsPfKJbUENwifUQMvI5fMMrATzBMZhIzyYdiUMVwz+L2WdDWzmtJQmZN7eonFPEukG8vJjYt5Vo=
