# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

variables:
- group: mabl-settings

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: $(Build.Repository.LocalPath)/script/cibuild
  displayName: 'executing CI build'

- script: $(Build.Repository.LocalPath)/script/mabl-deployment-integration.sh $(key) $(environment_id)
  displayName: 'executing test in mabl'

  
