# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec jekyll build
  displayName: 'executing jekyll build'

- script: bundle exec htmlproofer ./_site --disable-external
  displayName: 'executing htmlproofer'

- script: curl -s 'https://api.mabl.com/events/deployment' -u 'key:${key}' -H 'Content-Type:application/json' -d '{"environment_id":"${environment_id}","application_id":"${application_id}"}'
  displayName: 'triggering run in mabl'
  
