# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

variables:
- group: mabl-settings

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec jekyll build
  displayName: 'executing jekyll build'

- script: bundle exec htmlproofer ./_site --disable-external
  displayName: 'executing htmlproofer'

- script: |
    deployment_event = `curl -s 'https://api.mabl.com/events/deployment' -u 'key:$(key)' -H 'Content-Type:application/json' -d '{"environment_id":"$(environment_id)","application_id":"$(application_id)"}'`
    status_code=`echo ${deployment_event} | jq -r '.code'`
    if [ "${status_code}" != "200" ]; then
      echo "Deployment failed with ${status_code}" 1>&2
      return 1
    fi
    event_id=`echo ${deployment_event} | jq -r '.id'`
    echo '##vso[task.setvariable variable=event_id]${event_id}'
  displayName: 'triggering run in mabl'

  
